version: "3"
services:
  eprints:
    build:
      context: .
      dockerfile: Ubuntus.dockerfile
      args:
        EPRINTS_HOSTNAME: localhost
    ports:
      - "8081:80"
      - "3336:3306"
      - "8084:443"
    container_name: eprintsrepo
    volumes:
      - eprints:/usr/share/eprints
    stdin_open: true
    tty: true
volumes:
  eprints: